name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y libpng-dev zlib1g-dev libglew-dev freeglut3-dev libfreetype6-dev libvorbis-dev libogg-dev libopenal-dev bzip2 libxrandr-dev libcurl4-openssl-dev xorg-dev doxygen
    - name: make
      run: make -f source/linux/Makefile compile
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
